var blur_fragment_shader_src = [
'precision highp float;',
'uniform sampler2D u_image;',
'uniform vec2 windowSize;',
'varying vec2 fs_uv;',
'const int R = 1337;',
'void main(void) {',
'  vec4 col = vec4(0,0,0,0);',
'  int count = 0;',
'  for (int i = -R; i <= R; i++) {',
'    for (int j = -R; j <= R; j++) {',
'      vec2 uv = fs_uv + vec2(i, j) / windowSize;',
'      if (length(fs_uv * windowSize - uv * windowSize) < float(R) ) {',
'        col += texture2D(u_image, uv);',
'        count += 1;',
'      }',
'    }',
'  }',
'  gl_FragColor = col / float(count);',
'}',
].join("\n");
var fullscreen_quad_vertex_shader_src = [
'attribute vec4 vs_pos;',
'attribute vec2 vs_uv;',
'varying vec2 fs_uv;',
'void main(void) {',
'  gl_Position = vs_pos;',
'  fs_uv = vs_uv;',
'}',
].join("\n");
var lambert_fragment_shader_src = [
'precision highp float;',
'varying vec4 fs_col;',
'varying vec4 fs_nor;',
'varying vec4 lightVec;',
'void main(void) {',
'  float diffuseTerm = dot(normalize(fs_nor), normalize(lightVec));',
'  if (diffuseTerm < 0.0) {',
'    diffuseTerm = diffuseTerm * -0.3;',
'  }',
'  diffuseTerm = clamp(diffuseTerm, 0.0, 1.0);',
'  float ambientTerm = 0.2;',
'  float lightIntensity = diffuseTerm + ambientTerm;',
'  gl_FragColor = vec4(fs_col.rgb * lightIntensity, fs_col.a);',
'}',
].join("\n");
var lambert_vertex_shader_src = [
'attribute vec4 vs_pos;',
'attribute vec4 vs_col;',
'attribute vec4 vs_nor;',
'varying vec4 fs_col;',
'varying vec4 fs_nor;',
'uniform mat4 u_Model;',
'uniform mat4 u_ViewProj;',
'uniform mat4 u_InvTrans;',
'uniform vec4 u_Color;',
'varying vec4 lightVec;',
'const vec4 lightPos = vec4(20, 50, 30, 1);',
'void main(void) {',
'  vec4 modelposition = u_Model * vs_pos;',
'  gl_Position = u_ViewProj * modelposition;',
'  fs_col = u_Color;',
'  fs_nor = u_InvTrans * vs_nor;',
'  lightVec = lightPos - modelposition;',
'}',
].join("\n");
var noise_fragment_shader_src = [
'precision highp float; ',
'varying vec2 fs_uv;',
'uniform float u_Scale;',
'//',
'// Description : Array and textureless GLSL 2D simplex noise function.',
'//      Author : Ian McEwan, Ashima Arts.',
'//  Maintainer : ijm',
'//     Lastmod : 20110822 (ijm)',
'//     License : Copyright (C) 2011 Ashima Arts. All rights reserved.',
'//               Distributed under the MIT License. See LICENSE file.',
'//               https://github.com/ashima/webgl-noise',
'// ',
'vec3 mod289(vec3 x) {',
'  return x - floor(x * (1.0 / 289.0)) * 289.0;',
'}',
'vec2 mod289(vec2 x) {',
'  return x - floor(x * (1.0 / 289.0)) * 289.0;',
'}',
'vec3 permute(vec3 x) {',
'  return mod289(((x*34.0)+1.0)*x);',
'}',
'float snoise(vec2 v)',
'  {',
'  const vec4 C = vec4(0.211324865405187,  // (3.0-sqrt(3.0))/6.0',
'                      0.366025403784439,  // 0.5*(sqrt(3.0)-1.0)',
'                     -0.577350269189626,  // -1.0 + 2.0 * C.x',
'                      0.024390243902439); // 1.0 / 41.0',
'// First corner',
'  vec2 i  = floor(v + dot(v, C.yy) );',
'  vec2 x0 = v -   i + dot(i, C.xx);',
'// Other corners',
'  vec2 i1;',
'  //i1.x = step( x0.y, x0.x ); // x0.x > x0.y ? 1.0 : 0.0',
'  //i1.y = 1.0 - i1.x;',
'  i1 = (x0.x > x0.y) ? vec2(1.0, 0.0) : vec2(0.0, 1.0);',
'  // x0 = x0 - 0.0 + 0.0 * C.xx ;',
'  // x1 = x0 - i1 + 1.0 * C.xx ;',
'  // x2 = x0 - 1.0 + 2.0 * C.xx ;',
'  vec4 x12 = x0.xyxy + C.xxzz;',
'  x12.xy -= i1;',
'// Permutations',
'  i = mod289(i); // Avoid truncation effects in permutation',
'  vec3 p = permute( permute( i.y + vec3(0.0, i1.y, 1.0 ))',
'    + i.x + vec3(0.0, i1.x, 1.0 ));',
'  vec3 m = max(0.5 - vec3(dot(x0,x0), dot(x12.xy,x12.xy), dot(x12.zw,x12.zw)), 0.0);',
'  m = m*m ;',
'  m = m*m ;',
'// Gradients: 41 points uniformly over a line, mapped onto a diamond.',
'// The ring size 17*17 = 289 is close to a multiple of 41 (41*7 = 287)',
'  vec3 x = 2.0 * fract(p * C.www) - 1.0;',
'  vec3 h = abs(x) - 0.5;',
'  vec3 ox = floor(x + 0.5);',
'  vec3 a0 = x - ox;',
'// Normalise gradients implicitly by scaling m',
'// Approximation of: m *= inversesqrt( a0*a0 + h*h );',
'  m *= 1.79284291400159 - 0.85373472095314 * ( a0*a0 + h*h );',
'// Compute final noise value at P',
'  vec3 g;',
'  g.x  = a0.x  * x0.x  + h.x  * x0.y;',
'  g.yz = a0.yz * x12.xz + h.yz * x12.yw;',
'  return 130.0 * dot(m, g);',
'}',
'void main(void) {',
'  float amount = max(0.05, snoise(u_Scale*fs_uv));',
'  gl_FragColor = vec4(amount, amount, amount, 1);',
'}',
].join("\n");
var reachability_fragment_shader_src = [
'precision highp float;',
'uniform sampler2D back;',
'uniform sampler2D data;',
'uniform sampler2D obstacles;',
'uniform vec2 windowSize;',
'varying vec2 fs_uv;',
'const int D = 1337;',
'const float falloff = 0.005;',
'vec2 uv_clamp(vec2 vec) {',
'  return clamp(vec, vec2(0.001,0.001), vec2(0.999,0.999));',
'}',
'void main(void) {',
'  float current = texture2D(back, fs_uv).x;',
'  float xsize = 1.0 / windowSize.x;',
'  float ysize = 1.0 / windowSize.y;',
'  vec2 l = uv_clamp(vec2(fs_uv.x - xsize, fs_uv.y));',
'  vec2 r = uv_clamp(vec2(fs_uv.x + xsize, fs_uv.y));',
'  vec2 u = uv_clamp(vec2(fs_uv.x, fs_uv.y - ysize));',
'  vec2 d = uv_clamp(vec2(fs_uv.x, fs_uv.y + ysize));',
'  vec2 dl = uv_clamp(vec2(fs_uv.x - xsize, fs_uv.y - ysize));',
'  vec2 dr = uv_clamp(vec2(fs_uv.x + xsize, fs_uv.y - ysize));',
'  vec2 ul = uv_clamp(vec2(fs_uv.x - xsize, fs_uv.y + ysize));',
'  vec2 ur = uv_clamp(vec2(fs_uv.x + xsize, fs_uv.y + ysize));',
'  float col_l = texture2D(back, l).x + falloff;',
'  float col_r = texture2D(back, r).x + falloff;',
'  float col_u = texture2D(back, u).x + falloff;',
'  float col_d = texture2D(back, d).x + falloff;',
'  float col_dl = texture2D(back, dl).x + falloff*1.41421356;',
'  float col_dr = texture2D(back, dr).x + falloff*1.41421356;',
'  float col_ul = texture2D(back, ul).x + falloff*1.41421356;',
'  float col_ur = texture2D(back, ur).x + falloff*1.41421356;',
'  // float col = min(current, min(left, min(right, min(up, down))));',
'  float low = min(current, min(col_l, min(col_r, min(col_u, min(col_d, min(col_dl, min(col_dr, min(col_ul, col_ur))))))));',
'  // float sum = col_l+col_r+col_u+col_d+col_dl+col_dr+col_ul+col_ur;',
'  // float avg = sum / 8.0;',
'  // float col = min(avg, low);',
'  // float col = sum - 8.0;',
'  // float col = min(current, low + 0.01);',
'  // float col = 1.0 - (8.0 - sum)/7.1 + 0.01;',
'  // float infl = (1.0 - avg);',
'  float col = min(low, current) + texture2D(obstacles, fs_uv).x;',
'  gl_FragColor = vec4(col, col, col, 1.0);',
'}',
].join("\n");
var reachability_init_fragment_shader_src = [
'precision highp float;',
'// varying vec2 fs_uv;',
'void main(void) {',
'  gl_FragColor = vec4(0,0,0,1);',
'}',
].join("\n");
var reachability_init_vertex_shader_src = [
'attribute vec4 vs_pos;',
'// attribute vec2 vs_uv;',
'// varying vec2 fs_uv;',
'void main(void) {',
'  gl_Position = vs_pos;',
'  gl_PointSize = 5.0;',
'  // fs_uv = vs_uv;',
'}',
].join("\n");
var texture_fragment_shader_src = [
'precision highp float;',
'uniform sampler2D u_image;',
'varying vec4 fs_nor;',
'varying vec2 fs_uv;',
'varying vec4 lightVec;',
'uniform bool textureBound;',
'void main(void) {',
'  float diffuseTerm = dot(normalize(fs_nor), normalize(lightVec));',
'  if (diffuseTerm < 0.0) {',
'    diffuseTerm = diffuseTerm * -0.3;',
'  }',
'  diffuseTerm = clamp(diffuseTerm, 0.0, 1.0);',
'  float ambientTerm = 0.2;',
'  float lightIntensity = diffuseTerm + ambientTerm;',
'  vec4 col = texture2D(u_image, fs_uv);',
'  // gl_FragColor = vec4(col.rgb * lightIntensity, col.a);',
'  // gl_FragColor = vec4(1,1,1,1);',
'  gl_FragColor = vec4(col.rgb * lightIntensity, 1);',
'  if (!textureBound) {',
'    gl_FragColor = vec4(0.8,0.8,0.8,1);',
'  }',
'  // gl_FragColor = vec4(fs_uv, 0,1);',
'}',
].join("\n");
var texture_vertex_shader_src = [
'attribute vec4 vs_pos;',
'attribute vec4 vs_nor;',
'attribute vec2 vs_uv;',
'varying vec4 fs_nor;',
'varying vec2 fs_uv;',
'uniform mat4 u_Model;',
'uniform mat4 u_ViewProj;',
'uniform mat4 u_InvTrans;',
'varying vec4 lightVec;',
'const vec4 lightPos = vec4(20, 50, 30, 1);',
'void main(void) {',
'  fs_uv = vs_uv;',
'  vec4 modelposition = u_Model * vs_pos;',
'  gl_Position = u_ViewProj * modelposition;',
'  fs_nor = u_InvTrans * vs_nor;',
'  lightVec = lightPos - modelposition;',
'}',
].join("\n");
var velocity_fragment_shader_src = [
'precision highp float;',
'uniform sampler2D u_image0; ',
'uniform sampler2D u_image1;',
'uniform sampler2D u_weights; ',
'uniform float numAgents;',
'uniform vec2 windowSize;',
'uniform float u_gScale;',
'varying vec2 fs_uv;',
'const int R = 1337;',
'const int RES = 10;',
'int toID(vec4 col) {',
'  return int(col.r*float(RES)+0.5) + int(col.g*float(RES)+0.5)*RES + int(col.b*float(RES)+0.5)*RES*RES;',
'}',
'void main(void) {',
'  vec4 col = texture2D(u_image0, fs_uv);',
'  int id = toID(col);',
'  vec4 data = texture2D(u_image1, vec2(float(id)/(numAgents-0.5), 0.0));',
'  vec3 pos = vec3(data.xy, 0);',
'  vec3 gol = vec3(data.zw, 0);',
'  vec3 golVec = gol - pos;',
'  if (length(golVec.xy * windowSize) <= float(R)) {',
'    gl_FragColor = vec4(normalize(golVec) / u_gScale / float(R) * 0.3 + vec3(0.5,0.5,0), 1);',
'    return;',
'  }',
'  float totalWeight = 0.0;',
'  for (int i = -R; i < R; i++) {',
'    for (int j = -R; j < R; j++) {',
'      vec2 uv = fs_uv + vec2(i, j) / windowSize;',
'      col = texture2D(u_image0, uv);',
'      vec4 wt = texture2D(u_weights, uv);',
'      vec3 markerVec = (vec3(uv,0) - pos) * vec3(windowSize[0], windowSize[1], 1) * u_gScale; ',
'      if (',
'        id == toID(col) && ',
'        // i != 0 && ',
'        // j != 0 &&',
'        length(markerVec) <= float(R)',
'        // length(markerVec) >= 0.25',
'        ) {',
'        // ',
'        // float weight = 1.0 + dot(normalize(markerVec), normalize(golVec));',
'        float weight = min(1.0,wt[0]);',
'        totalWeight += weight;',
'      }',
'    }',
'  }',
'  if (totalWeight < 0.01) {',
'    gl_FragColor = vec4(0.5, 0.5, 0, 1);',
'    return;',
'  }',
'  vec3 cumul = vec3(0,0,0);',
'  for (int i = -R; i < R; i++) {',
'    for (int j = -R; j < R; j++) {',
'      vec2 uv = fs_uv + vec2(i, j) / windowSize;',
'      col = texture2D(u_image0, uv);',
'      vec4 wt = texture2D(u_weights, uv);',
'      vec3 markerVec = (vec3(uv,0) - pos) * vec3(windowSize[0], windowSize[1], 1)  * u_gScale; /// float(R);  ',
'      if (',
'        id == toID(col) && ',
'        // i != 0 && ',
'        // j != 0 && ',
'        length(markerVec) <= float(R)',
'        // length(markerVec) >= 0.25',
'        ) {',
'        // float weight = 1.0 + dot(normalize(markerVec), normalize(golVec));',
'        float weight = min(1.0,wt[0]);',
'        weight = weight / totalWeight / float(R) / u_gScale;',
'        cumul += markerVec * weight;',
'      }',
'    }',
'  }',
'  gl_FragColor = vec4(cumul*0.5 + vec3(0.5,0.5,0), 1);',
'  return;',
'}',
].join("\n");
var velocity_vertex_shader_src = [
'attribute vec4 vs_pos;',
'attribute vec2 vs_uv;',
'varying vec2 fs_uv;',
'void main(void) {',
'  gl_Position = vs_pos;',
'  gl_PointSize = 2.0;',
'  fs_uv = vs_uv;',
'}',
].join("\n");
var voronoi_fragment_shader_src = [
'precision highp float;',
'varying vec4 fs_col;',
'void main(void) {',
'  gl_FragColor = fs_col;',
'}',
].join("\n");
var voronoi_refine_fragment_shader_src = [
'precision highp float;',
'uniform sampler2D u_image;',
'uniform vec2 windowSize;',
'uniform float u_gScale;',
'varying vec2 fs_uv;',
'const int R = 1337;',
'void main(void) {',
'  vec4 col = texture2D(u_image, fs_uv);',
'  gl_FragColor = col;',
'  for (int i = -R; i < R; i++) {',
'    for (int j = -R; j < R; j++) {',
'      vec2 uv = fs_uv + vec2(i, j) / windowSize;',
'      // vec2 dir = uv - fs_uv;',
'      // float dist = length(dir);',
'      // dir = normalize(dir);',
'      // for (int d = 0; d < R; d++) {',
'      //   vec2 r_uv = fs_uv + ( float(d) / max(windowSize.x, windowSize.y) )*dir;',
'      //   vec4 col2 = texture2D(u_image, r_uv);',
'      //   if (col != col2) {',
'      //     gl_FragColor = vec4(1,1,1,1);',
'      //     return;',
'      //   }',
'      // }',
'      // for (float d = 0.0; d < float(R) / max(windowSize.x, windowSize.y); d += 1.0/min(windowSize.x, windowSize.y)) {',
'      //   if (d < dist) {',
'      //     vec2 r_uv = uv + d*dir;',
'      //     vec4 col2 = texture2D(u_image, r_uv);',
'      //     if (col != col2) {',
'      //       gl_FragColor = vec4(1,1,1,1);',
'      //       return;',
'      //     }',
'      //   }',
'      // }',
'      vec4 col2 = texture2D(u_image, uv);',
'      if (col != col2) {',
'        gl_FragColor = vec4(1,1,1,1);',
'        return;',
'      }',
'    }',
'  }',
'}',
].join("\n");
var voronoi_vertex_shader_src = [
'attribute vec4 vs_pos;',
'attribute vec3 vs_offset;',
'attribute vec3 vs_velocity;',
'attribute vec3 vs_id;',
'varying vec4 fs_col;',
'uniform mat4 u_ViewProj;',
'mat4 rotationMatrix(vec3 axis, float angle)',
'{',
'    axis = normalize(axis);',
'    float s = sin(angle);',
'    float c = cos(angle);',
'    float oc = 1.0 - c;',
'    ',
'    return mat4(oc * axis.x * axis.x + c,           oc * axis.x * axis.y - axis.z * s,  oc * axis.z * axis.x + axis.y * s,  0.0,',
'                oc * axis.x * axis.y + axis.z * s,  oc * axis.y * axis.y + c,           oc * axis.y * axis.z - axis.x * s,  0.0,',
'                oc * axis.z * axis.x - axis.y * s,  oc * axis.y * axis.z + axis.x * s,  oc * axis.z * axis.z + c,           0.0,',
'                0.0,                                0.0,                                0.0,                                1.0);',
'}',
'float atan2(in float y, in float x)',
'{',
'    bool s = (abs(x) > abs(y));',
'    float v1 = 3.14159265/2.0 - atan(x,y);',
'    float v2 = atan(x,y);',
'    return (1.0-float(s))*v1 + float(s)*v2;',
'}',
'void main(void) { ',
'  fs_col = vec4(vs_id, 1);',
'  vec3 pos = vec3(vs_pos.x, 0, vs_pos.z);',
'  vec3 vel = normalize(vs_velocity);',
'  mat4 rot = rotationMatrix(vec3(0,1,0), atan2(-vel.z, vel.x));',
'  float fac = 2.0 + dot(normalize(pos), normalize(vs_velocity));',
'  fac = fac / 3.0;',
'  pos = vec3(rot * vs_pos);',
'  gl_Position = u_ViewProj * (vec4(pos,1) + vec4(vs_offset, 0));',
'}',
].join("\n");
var weight_fragment_shader_src = [
'precision highp float;',
'uniform sampler2D u_image0; ',
'uniform sampler2D u_image1;',
'uniform sampler2D u_comfortMap; ',
'uniform bool u_useComfortMap;',
'uniform vec2 windowSize;',
'uniform float numAgents;',
'varying vec2 fs_uv;',
'const int R = 1337;',
'const int RES = 10;',
'int toID(vec4 col) {',
'  return int(col.r*float(RES)+0.5) + int(col.g*float(RES)+0.5)*RES + int(col.b*float(RES)+0.5)*RES*RES;',
'}',
'void main(void) {',
'  vec4 col = texture2D(u_image0, fs_uv);',
'  int id = toID(col);',
'  vec4 data = texture2D(u_image1, vec2(float(id)/(numAgents-0.5), 0.0));',
'  vec3 pos = vec3(data.xy, 0);',
'  vec3 gol = vec3(data.zw, 0);',
'  vec3 golVec = gol - pos;',
'  vec3 marker = 2.0*vec3(fs_uv, 0) - vec3(1,1,0);',
'  vec3 markerVec = vec3(fs_uv, 0) - pos;',
'  float weight = 1.0 + dot(normalize(markerVec), normalize(golVec));',
'  weight *= (',
'    (1.0 - float(u_useComfortMap)) + ',
'    float(u_useComfortMap)*texture2D(u_comfortMap, fs_uv).x',
'  );',
'  bool mask = length(markerVec) < float(R) / windowSize.x;',
'  weight = float(mask) * weight;',
'  gl_FragColor = vec4(weight,weight,weight,1);',
'}',
].join("\n");
